# Generated by Django 4.2.10 on 2024-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0003_alter_students_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='parent_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
