# Generated by Django 4.2.10 on 2024-02-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('grade', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_occupation', models.CharField(max_length=100)),
                ('parent_address', models.TextField()),
                ('guidance_phone', models.CharField(max_length=10)),
                ('parent_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
