# Generated by Django 4.2.10 on 2024-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0002_rename_guidance_phone_students_guardian_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
