# Generated by Django 4.2.10 on 2024-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='administrator_profile_pics/'),
        ),
    ]
